### ISSUE TITLE
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1001] and a Java object with shape [1, 1002].

### ISSUE THREAD

**Issue by PraveenMuthu22** [soum-io/TensorFlowLiteInceptionTutorial#1]
I'm getting this error when classify button is pressed. The app crashes.
Full error
```
2020-02-22 11:43:12.836 9177-9177/com.soumio.inceptiontutorial E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.soumio.inceptiontutorial, PID: 9177
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1001] and a Java object with shape [1, 1002].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:360)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:317)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:195)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:275)
        at com.soumio.inceptiontutorial.Classify$3.onClick(Classify.java:180)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by PraveenMuthu22** [comment]
I have mistakenly created a space in labels.txt. Sorry.
